version: "3.3"

services:
  node:
    container_name: google-node
    image: node:14-buster
    user: 1000:1000
    working_dir: '/usr/share'
    volumes:
      - '.:/usr/share'
      
  front:
    container_name: google-front
    image: uotz/vuejs
    volumes:
      - './front:/home/app'
    ports:
      - '8080:8080'
    networks:
      - app-network

  php:
    image: uotz/php7.4-nginx
    container_name: google-php
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./back:/home/app
      - ./.docker/nginx/default.conf:/etc/nginx/sites-available/default
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: google-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "google"
      MYSQL_USER: "google"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SERVER_MAXPAYLOADBYTES: 20485760
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.11.0
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   volumes:
  #     - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - app-network

networks:
  app-network:
    name: google-network
    driver: bridge

volumes:
  mysql-data:
    driver: local
  esdata:
    driver: local

